Clean up.

diff --git a/private_dot_local/bin/executable_ollama-sync b/private_dot_local/bin/executable_ollama-sync
--- a/private_dot_local/bin/executable_ollama-sync
+++ b/private_dot_local/bin/executable_ollama-sync
@@ -19,7 +19,7 @@ set -- "${args_cleaned[@]}"
 
 if ! command -v ollama &> /dev/null; then
   ERROR="$BOLD$BRIGHT_WHITE$BG_RED"
-  ansi::err "${ERROR}ollama is not installed${RESET_ALL}"
+  ansi::err "${ERROR}ollama is not installed${RESET_ALL}" || exit 1
 fi
 
 ollama list | tail -n +2 | awk '{print $1}' | while read -r model; do
