Updated code for new version of `options.bash`.

diff --git a/private_dot_local/bin/executable_jot b/private_dot_local/bin/executable_jot
--- a/private_dot_local/bin/executable_jot
+++ b/private_dot_local/bin/executable_jot
@@ -82,7 +82,8 @@ if [ -z "${1:-}" ] || [[ "$args_command" == "list" ]]; then
   ansi::out "Listing available files:"
   echo
   if ! aws s3 ls "s3://$JOT_AWS_S3_BUCKET/$prefix"; then
-    ansi::err "${ERROR}The previous command failed: make sure that the bucket ${REVERSE}${JOT_AWS_S3_BUCKET}${RESET_REVERSE} exists and accessible.${RESET_ALL}" || exit 1
+    ansi::warn "${ERROR}The previous command failed: make sure that the bucket ${REVERSE}${JOT_AWS_S3_BUCKET}${RESET_REVERSE} exists and accessible.${RESET_ALL}"
+    exit 1
   fi
   echo
   ansi::out "To edit a file: jot ${ITALIC}file_name${RESET_ALL}"
